NAME = MEGAPHONE
SRC = megaphone.cpp
FLAGS = -Wall -Wextra -Werror -std=c++98

all:
		@clear
		@c++ $(FLAGS) $(SRC) -o $(NAME)
		@echo "Checking batteries"
		@echo "Testing testing"
		@echo "Megaphone roll out"

clean:
		@clear
		@rm -f MEGAPHONE
		@echo "Tidy"

fclean:
		@rm -f MEGAPHONE
		@echo "Real tidy"

re: fclean all
